services:
  nginx:
    hostname: inception-nginx
    image: inception-nginx
    container_name: inception-nginx
    build: ./requirements/nginx
    env_file: variables.env
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      # TODO: Change when testing in VM
      - /home/mateo/workspace/inception/srcs/requirements/wordpress/wordpress:/srv/www/wordpress/

  mariadb:
    hostname: inception-mariadb
    image: inception-mariadb
    container_name: inception-mariadb
    build: ./requirements/mariadb
    env_file: variables.env
    networks:
      - inception
    volumes:
      # TODO: Change when testing in VM
      - /home/mateo/workspace/inception/srcs/requirements/mariadb/data:/var/lib/mysql

  wordpress:
    hostname: inception-wordpress
    image: inception-wordpress
    container_name: inception-wordpress
    build: ./requirements/wordpress
    env_file: variables.env
    networks:
      - inception
    volumes:
      # TODO: Change when testing in VM
      - /home/mateo/workspace/inception/srcs/requirements/wordpress/wordpress:/srv/www/wordpress/

networks:
  inception:
    name: inception
